name: Mirror to Hugging Face

on:
  push:
    branches:
      - main   # only run on main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # ensure full history (avoids shallow update errors)

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push to Hugging Face
        run: |
          git remote add hf https://huggingface.co/spaces/fmazzoni/boston311
          echo "https://fmazzoni:${{ secrets.HF_TOKEN }}@huggingface.co" > ~/.git-credentials
          git config credential.helper store
          git push hf main --force
